apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-xemw
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zfzs-tenant/rhtap-demo-app/hacbs-test-project-xemw@sha256:b0d46fafe169910720629123ad6adefbb79488caa9af81b43a8549c9b6ed2076
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
