apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-xemw
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zfzs-tenant/rhtap-demo-app/hacbs-test-project-xemw@sha256:cdb14d852f892da50408bd1883c781933d70da822e4d295847d787527c0b0ff6
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
